POST http://localhost:8081/user/entries
Content-Type: application/json

{
    "userid": "66e7cc598ba469d6a4400983",
    "amount": 100,
    "type": "income",
    "date": "2024-09-16T07:43:33Z",
    "isRecurring": true
}
####


POST http://localhost:8081/user/entries
Content-Type: application/json

{
    "userid": "66e7cc598ba469d6a4400983",
    "amount": 200,
    "type": "expense",
    "date": "2024-09-16T07:43:33Z",
    "comments": "Hello"
    
}

####
GET http://localhost:8081/user/entries
Content-Type: application/json


####
POST http://localhost:8081/budget/daily
Content-Type: application/json

{
    "userid": "66e7cc598ba469d6a4400983",
    "amount": 50
}